
enum previoCarReviewsOptions {
    VERY_BAD_STATE = "VERY_BAD_STATE",
    VERY_DIRTY = "VERY_DIRTY",
    REDUCED_TRUNK_SPACE = "REDUCED_TRUNK_SPACE",
    NO_SEATBELTS = "NO_SEATBELTS",
    NO_AIR_CONDITIONING = "NO_AIR_CONDITIONING",
    UNCOMFORTABLE_SEATS = "UNCOMFORTABLE_SEATS",
    BAD_STATE = "BAD_STATE",
    DIRTY = "DIRTY",
    AIR_CONDITIONING_WORKING_BADLY = "AIR_CONDITIONING_WORKING_BADLY",
    SEATBELTS_MISSING = "SEATBELTS_MISSING",
    GOOD_STATE = "GOOD_STATE",
    CLEAN = "CLEAN",
    GOOD_TRUNK_SPACE = "GOOD_TRUNK_SPACE",
    COMFORTABLE_SEATS = "COMFORTABLE_SEATS",
    AIR_CONDITIONING_WORKING_WELL = "AIR_CONDITIONING_WORKING_WELL",
    SEATBELTS = "SEATBELTS",
    VERY_GOOD_STATE = "VERY_GOOD_STATE",
    VERY_CLEAN = "VERY_CLEAN",
    IMPECCABLE = "IMPECCABLE",
    BIG_TRUNK_SPACE = "BIG_TRUNK_SPACE",
    VERY_COMFORTABLE_SEATS = "VERY_COMFORTABLE_SEATS",
    AIR_CONDITIONING_WORKING_PERFECTLY = "AIR_CONDITIONING_WORKING_PERFECTLY",
}

export default previoCarReviewsOptions;