enum ReviewsOptions{
    DISRESPECTFUL = "DISRESPECTFUL",
    INAPPROPRIATE_BEHAVIOUR = "INAPPROPRIATE_BEHAVIOUR",
    UNPUNCTUAL = "UNPUNCTUAL",
    DIRTY = "DIRTY",
    NOT_FRIENDLY = "NOT_FRIENDLY",
    UNCOMMUNICATIVE = "UNCOMMUNICATIVE",
    BAD_BEHAVIOUR = "BAD_BEHAVIOUR",
    BAD_ATTITUDE = "BAD_ATTITUDE",
    ACCEPTABLE_BEHAVIOUR = "ACCEPTABLE_BEHAVIOUR",
    FRIENDLY = "FRIENDLY",
    PUNCTUAL = "PUNCTUAL",
    CLEAN = "CLEAN",
    ACCEPTABLE_ATTITUDE = "ACCEPTABLE_ATTITUDE",
    VERY_FRIENDLY = "VERY_FRIENDLY",
    CONSIDERATE = "CONSIDERATE",
    RESPONSIBLE = "RESPONSIBLE",
    GOOD_COMPANY = "GOOD_COMPANY"
}

export default ReviewsOptions;