const enum Status {
    DELETE = "DELETE",
    UNCONFIRMED = "UNCONFIRMED",
    PENDING = "PENDING",
    ACCEPTED = "ACCEPTED",
    CANCEL = "CANCEL",
    REJECTED = "REJECTED",
    FINISHED = "FINISHED",
    NOT_STARTED = "NOT_STARTED",
    IN_PROGRESS = "IN_PROGRESS",
}

export default Status;