INSERT INTO provinces (id, name) VALUES (1, 'CABA');

INSERT INTO cities (name, province_id) VALUES ('Agronomía', 1);
INSERT INTO cities (name, province_id) VALUES ('Almagro', 1);
INSERT INTO cities (name, province_id) VALUES ('Balvanera', 1);
INSERT INTO cities (name, province_id) VALUES ('Barracas', 1);
INSERT INTO cities (name, province_id) VALUES ('Belgrano', 1);
INSERT INTO cities (name, province_id) VALUES ('Boedo', 1);
INSERT INTO cities (name, province_id) VALUES ('Caballito', 1);
INSERT INTO cities (name, province_id) VALUES ('Chacarita', 1);
INSERT INTO cities (name, province_id) VALUES ('Coghlan', 1);
INSERT INTO cities (name, province_id) VALUES ('Colegiales', 1);
INSERT INTO cities (name, province_id) VALUES ('Constitución', 1);
INSERT INTO cities (name, province_id) VALUES ('Flores', 1);
INSERT INTO cities (name, province_id) VALUES ('Floresta', 1);
INSERT INTO cities (name, province_id) VALUES ('La Boca', 1);
INSERT INTO cities (name, province_id) VALUES ('La Paternal', 1);
INSERT INTO cities (name, province_id) VALUES ('Liniers', 1);
INSERT INTO cities (name, province_id) VALUES ('Mataderos', 1);
INSERT INTO cities (name, province_id) VALUES ('Monte Castro', 1);
INSERT INTO cities (name, province_id) VALUES ('Montserrat', 1);
INSERT INTO cities (name, province_id) VALUES ('Nueva Pompeya', 1);
INSERT INTO cities (name, province_id) VALUES ('Núñez', 1);
INSERT INTO cities (name, province_id) VALUES ('Palermo', 1);
INSERT INTO cities (name, province_id) VALUES ('Parque Avellaneda', 1);
INSERT INTO cities (name, province_id) VALUES ('Parque Chacabuco', 1);
INSERT INTO cities (name, province_id) VALUES ('Parque Chas', 1);
INSERT INTO cities (name, province_id) VALUES ('Parque Patricios', 1);
INSERT INTO cities (name, province_id) VALUES ('Puerto Madero', 1);
INSERT INTO cities (name, province_id) VALUES ('Recoleta', 1);
INSERT INTO cities (name, province_id) VALUES ('Retiro', 1);
INSERT INTO cities (name, province_id) VALUES ('Saavedra', 1);
INSERT INTO cities (name, province_id) VALUES ('San Cristóbal', 1);
INSERT INTO cities (name, province_id) VALUES ('San Nicolás', 1);
INSERT INTO cities (name, province_id) VALUES ('San Telmo', 1);
INSERT INTO cities (name, province_id) VALUES ('Versalles', 1);
INSERT INTO cities (name, province_id) VALUES ('Villa Crespo', 1);
INSERT INTO cities (name, province_id) VALUES ('Villa Devoto', 1);
INSERT INTO cities (name, province_id) VALUES ('Villa General Mitre', 1);
INSERT INTO cities (name, province_id) VALUES ('Villa Lugano', 1);
INSERT INTO cities (name, province_id) VALUES ('Villa Luro', 1);
INSERT INTO cities (name, province_id) VALUES ('Villa Ortúzar', 1);
INSERT INTO cities (name, province_id) VALUES ('Villa Pueyrredón', 1);
INSERT INTO cities (name, province_id) VALUES ('Villa Real', 1);
INSERT INTO cities (name, province_id) VALUES ('Villa Riachuelo', 1);
INSERT INTO cities (name, province_id) VALUES ('Villa Santa Rita', 1);
INSERT INTO cities (name, province_id) VALUES ('Villa Soldati', 1);
INSERT INTO cities (name, province_id) VALUES ('Villa Urquiza', 1);
INSERT INTO cities (name, province_id) VALUES ('Villa del Parque', 1);
INSERT INTO cities (name, province_id) VALUES ('Vélez Sársfield', 1);
