INSERT INTO provinces (province_id, name) VALUES (1, 'CABA');

INSERT INTO cities (city_id, name, province_id) VALUES (1, 'Agronomía', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (2, 'Almagro', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (3, 'Balvanera', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (4, 'Barracas', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (5, 'Belgrano', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (6, 'Boedo', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (7, 'Caballito', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (8, 'Chacarita', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (9, 'Coghlan', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (10, 'Colegiales', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (11, 'Constitución', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (12, 'Flores', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (13, 'Floresta', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (14, 'La Boca', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (15, 'La Paternal', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (16, 'Liniers', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (17, 'Mataderos', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (18, 'Monte Castro', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (19, 'Montserrat', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (20, 'Nueva Pompeya', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (21, 'Núñez', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (22, 'Palermo', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (23, 'Parque Avellaneda', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (24, 'Parque Chacabuco', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (25, 'Parque Chas', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (26, 'Parque Patricios', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (27, 'Puerto Madero', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (28, 'Recoleta', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (29, 'Retiro', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (30, 'Saavedra', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (31, 'San Cristóbal', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (32, 'San Nicolás', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (33, 'San Telmo', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (34, 'Versalles', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (35, 'Villa Crespo', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (36, 'Villa Devoto', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (37, 'Villa General Mitre', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (38, 'Villa Lugano', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (39, 'Villa Luro', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (40, 'Villa Ortúzar', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (41, 'Villa Pueyrredón', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (42, 'Villa Real', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (43, 'Villa Riachuelo', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (44, 'Villa Santa Rita', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (45, 'Villa Soldati', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (46, 'Villa Urquiza', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (47, 'Villa del Parque', 1);
INSERT INTO cities (city_id, name, province_id) VALUES (48, 'Vélez Sársfield', 1);
